import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Time Is Money";
    max-height: 380px;
    max-width: 400px;
    min-height: 380px;

    // constants
    property <int> bold: 700;
    property <int> normal: 400;


    callback request-acc-data();
    callback choose-file();
    callback put_me_into_excel();
    in property <string> filename;
    in-out property <string> filepath;
    property <string> state: "Nothing happened yet";

    VerticalBox {
        spacing: 20px;
        padding: 16px;

        // Header Section
        Rectangle {
            padding: 16px;
            height: 80px;
            HorizontalBox {
                alignment: center;
                spacing: 8px;
                Text {
                    vertical-alignment: center;
                    text: "⏱️ Time Is Money";
                    font-size: 24px;
                    color: #6c757d;
                    font-weight: root.bold;
                }
            }
        }

        // File Info Section
        Rectangle {
            background: #f5f7fa;
            border-radius: 8px;
            padding: 12px;
            height: 40px;
            HorizontalBox {
                Text {
                    text: "Selected File: " + filename;
                    vertical-alignment: center;
                    font-size: 14px;
                    color: #6c757d;
                }
            }
        }

        // Shows current state of program
        Rectangle {
            background: #f5f7fa;
            border-radius: 8px;
            padding: 12px;
            height: 40px;
            HorizontalBox {
                Text {
                    text: state;
                    vertical-alignment: center;
                    font-size: 12px;
                    color: #6c757d;
                    font-weight: normal;
                }
            }
        }

        // Action Buttons Section
        Rectangle {
            border-radius: 8px;

            HorizontalBox {
                padding: 0px;
                alignment: center;
                Button {
                    width: 192px;
                    height: 52px;
                    text: "Choose File";
                    clicked => {
                        state = "Nice choice";
                        root.choose-file();
                    }
                }

                Button {
                    width: 192px;
                    height: 52px;
                    text: "Extract Data";
                    clicked => {
                        root.request-acc-data();
                        root.put_me_into_excel();
                        state = "Data is in spreadsheet now";
                    }
                }
            }
        }

        // Footer Section
        Rectangle {
            height: 40px;
            background: #f1f3f5;
            border-radius: 8px;
            padding: 12px;
            HorizontalBox {
                alignment: center;
                spacing: 4px;
                Text {
                    text: "Made with ❤️ by Yaroslav";
                    font-size: 12px;
                    vertical-alignment: center;
                    color: #adb5bd;
                }
                Text {
                    text: "v1.1";
                    font-size: 12px;
                    vertical-alignment: center;
                    color: #ced4da;
                }
            }
        }
    }
}
